const videos=document.querySelectorAll('video');
videos.forEach(video=>{
    video.addEventListener('mouseenter',e=>{
        if(e.target.getAttribute('id')==='1'){
            videos[1].style.opacity='0'
            videos[2].style.opacity='0'
        }
        if(e.target.getAttribute('id')==='2'){
            videos[0].style.display='none'
            videos[2].style.opacity='0'
            videos[3].style.opacity='0'
        }
        if(e.target.getAttribute('id')==='3'){
            videos[0].style.opacity='0'
            videos[1].style.opacity='0'
        }
        if(e.target.getAttribute('id')==='4'){
            videos[0].style.opacity='0'
            videos[1].style.opacity='0'
            videos[2].style.display='none'
        }
        if((e.target.getAttribute('id')==='1')||(e.target.getAttribute('id')==='4')){
            e.target.volume=.35
        }
        e.target.play().then(()=>{
            console.log('cb')
        })
        .catch(()=>{
            console.log('cpb')
            alert('Veuillez activer "Lire automatiquement des médias" dans votre navigateur et rafraichir la page')
        })
    });
    video.addEventListener('mouseleave',e=>{
        e.target.pause();
        if(e.target.getAttribute('id')==='1'){
            videos[1].removeAttribute('style')
            videos[2].removeAttribute('style')
        }
        if(e.target.getAttribute('id')==='2'){
            videos[0].removeAttribute('style')
            videos[2].removeAttribute('style')
            videos[3].removeAttribute('style')
        }
        if(e.target.getAttribute('id')==='3'){
            videos[0].removeAttribute('style')
            videos[1].removeAttribute('style')
        }
        if(e.target.getAttribute('id')==='4'){
            videos[0].removeAttribute('style')
            videos[1].removeAttribute('style')
            videos[2].removeAttribute('style')
        }
    });
    video.addEventListener('ended',e=>{
        e.target.currentTime=0;
        e.target.play();
    });
    video.onerror=()=>{
        alert('Veuillez activer "Lire automatiquement des médias" dans votre navigateur')
    };
});
